application_prod:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_DEV_HOST') }}"
      port: 5432
      user: postgres
      password: "{{ env_var('DBT_DEV_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DEV_DBNAME') }}"
      schema: "{{ env_var('DBT_DEV_SCHEMA') }}"
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('DBT_PROD_HOST') | default(env_var('DBT_DEV_HOST')) }}"
      port: 5432
      user: postgres
      password: "{{ env_var('DBT_PROD_PASSWORD') | default(env_var('DBT_DEV_PASSWORD')) }}"
      dbname: "{{ env_var('DBT_PROD_DBNAME') | default(env_var('DBT_DEV_DBNAME')) }}"
      schema: "{{ env_var('DBT_PROD_SCHEMA') | default('schema_prod') }}"
      threads: 7

  target: dev